# Generated by Django 5.0.3 on 2024-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição')),
                ('requeriments', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Requisitos')),
                ('salary', models.FloatField(verbose_name='Salário')),
                ('workload', models.CharField(max_length=10, verbose_name='Carga Horária')),
            ],
        ),
    ]
