# Generated by Django 5.0.3 on 2024-04-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True, verbose_name='Data de início')),
                ('date_end', models.DateTimeField(verbose_name='Data de término')),
                ('candidates', models.ManyToManyField(blank=True, related_name='candidates', to=settings.AUTH_USER_MODEL, verbose_name='Cadidatos')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='jobs.job', verbose_name='Vaga')),
            ],
        ),
    ]
